services:
  - type: web
    name: mealstack-backend
    env: java
    buildCommand: cd Campus-Canteen-Management-System-main/Backend/backend && mvn clean package -DskipTests
    startCommand: cd Campus-Canteen-Management-System-main/Backend/backend && java -jar target/cms_backend-0.0.1.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: mealstack-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_TIME
        value: 86400000
    healthCheckPath: /actuator/health
